[package]
org = "ballerina"
name = "openapi"
version = "2.0.0"


[dependencies]
"ballerina/io" = "0.5.2"
"ballerina/log" = "1.0.2"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"

[platform]
target = "java11"

