[project]
org-name = "ballerina"
version = "2.0.0"

[dependencies]
"ballerina/io" = "0.5.2"
"ballerina/log" = "1.0.2"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "openapi"
    version = "2.0.0-Preview6-SNAPSHOT"
    path = "../openapi-validator/build/libs/openapi-validator-2.0.0-Preview6-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["openapi"]
