[package]
org= "ballerina"
name= "integrationTest"
version= "2.0.0"

[build-options]
observability-included=true

[[dependency]]
org= "ballerina"
name= "system"
version=

[[dependency]]
org= "ballerina"
name= "log"
version=

[[dependency]]
org= "ballerina"
name= "stringutils"
version=

[[dependency]]
org= "ballerina"
name= "config"
version=