[package]
org= "ballerina"
name= "integrationTest"
version= "2.0.0"

[build-options]
observability-included=true

[[dependency]]
org= "ballerina"
name= "system"
version= @stdlib.system.version@

[[dependency]]
org= "ballerina"
name= "log"
version= @stdlib.log.version@

[[dependency]]
org= "ballerina"
name= "stringutils"
version= @stdlib.stringutils.version@

[[dependency]]
org= "ballerina"
name= "config"
version= @stdlib.config.version@